#' Construct a Makefile
#'
#' This function constructs a \code{Makefile} for various objects.
#'
#' @param web The object to construct the \code{Makefile} for
#' @return A Makefile
#'
#' @importFrom MakefileR make_rule make_def make_group make_comment make_text
#' @export
makify <- function(web = rpkgweb()) {
  web <- as.rpkgweb(web)

  g <- make_group(make_comment("Autogenerated using rpkgweb"), sep = "")
  if (Sys.getenv("RPKGWEB_QUALIFY") != "")
    g <- g +
      make_group(
        make_comment("Use alternative loading method for rpkgweb library"),
        make_def("RPKGWEB_QUALIFY", Sys.getenv("RPKGWEB_QUALIFY")),
        make_text("export RPKGWEB_QUALIFY")
      )
  g +
    make_def("R_USER_LIBRARY", .libPaths()[[1L]]) +
    make_group(
      make_comment("Universal targets"),
      make_rule("all", "all-install"),
      make_rule("all-install", web$packages %>% names),
      make_rule("all-check", sprintf("check-%s", web$packages %>% names))
    ) +
    make_rule(".FORCE") +
    make_rule("Makefile", ".FORCE",
              "write_makefile()" %>%
                .rpkgweb_qualify() %>% Rscript_call()) +
    make_rule(lib_desc_path("%"), code_desc_path("%"),
              "check_up('$(patsubst %/,%,$(dir $<))')" %>%
                .rpkgweb_qualify() %>% Rscript_call()) +
    make_rule(check_log_path("%"), c(code_desc_path("%"), lib_desc_path("%")),
              paste0("dir.create('", check_dir, "', showWarnings = FALSE, recursive = TRUE); ",
                     "devtools::check('$(patsubst %/,%,$(dir $<))')") %>%
                Rscript_call()) +
    (
      web$packages %>%
        names %>%
        lapply(. %>% { make_rule(., lib_desc_path(.)) } ) %>%
        make_group(make_comment("Convenience targets"), .dots = .)
    ) +
    (
      web$packages %>%
        names %>%
        lapply(. %>% { make_rule(sprintf("check-%s", .), check_log_path(.)) } ) %>%
        make_group(make_comment("Convenience targets for checking"), .dots = .)
    ) +
    makify_deps(web %>% deps_df)
}

#' @importFrom MakefileR make_rule
makify_deps <- function(y) {
  y <- y %>% subset(internal)
  rules <- mapply(y$package %>% lib_desc_path,
                  y$dep_package %>% lib_desc_path,
                  FUN = make_rule, SIMPLIFY = FALSE)
  Reduce(c, rules, init = make_group(make_comment("Dependencies")))
}

check_dir <- "rpkgweb-check"
check_log_path <- . %>% sprintf("%s.Rcheck", .) %>% file.path(check_dir, ., "00check.log")
lib_desc_path <- . %>% file.path("${R_USER_LIBRARY}", ., "DESCRIPTION")
code_desc_path <- . %>% file.path(., "DESCRIPTION")

.rpkgweb_qualify <- function(expr) {
  paste0(Sys.getenv("RPKGWEB_QUALIFY", "rpkgweb::"), expr)
}

Rscript_call <- function(expr) {
  sprintf("Rscript -e \"%s\"", expr)
}
